### ISSUE TITLE
Prototype

### ISSUE THREAD

**Issue by ccoria** [NinjaReader/AndroidNinjaReader#5]
Hey @alonrz and @mvinceable, I'm creating the prototype on another repo, as soon as I have a minimum done there, I will integrate here.

I also commented on our doc that the instapaper API requires approval. I asked them already but didn't get it answered.

If any of you have plans to do any interface, please talk to me to avoid overlapping work. =)

**Comment by alonrz** [comment]
Hey @ccoria, I spoke with @mvinceable and we want to work on some UI too (sent you an email earlier today).
Please let us know which UI parts you're doing so we do not overlap. 
UI components needed:
- page to view all articles
- page to read a single article
- profile page
- social/statistics about reading habits.

Unless I hear from you, I will start working on the page to list all articles and Vince will do the profile page.

**Comment by ccoria** [comment]
That's ok, I actually have done an initial page here https://github.com/ccoria/NinjaReaderDraft.

Just a fake prototype with a list and a populated model.. Do you want do split this UI work?

**Comment by ccoria** [comment]
![screen shot 2015-02-23 at 9 14 51 pm](https://cloud.githubusercontent.com/assets/69435/6343658/657e54fc-bba1-11e4-8b2e-e226c271b23c.png)

**Comment by mvinceable** [comment]
Wow that mock looks awesome!  Nice logo too.  I was playing around with the
readability API and we can extract things like:
1. author
2. excerpt
3. word count
4. date published
5. image url
6. title

...just from an article URL.  The cool thing is there's no authentication
necessary.

Once  a user marks an article as read, we can add that to their stats.

Let's sync up more tomorrow.

Thanks,
Vince

**Comment by ccoria** [comment]
Thanks! Great job on the main project as well guys, I am able to run it here..

The logo is a CC logo. We just need to add attribution and link if we want to use it for real:
http://www.flaticon.com/free-icon/spy-japanese-ninja_13143

I also added the "reading article" to the prototype project, Let's figure out how to merge our work tomorrow. I'll try to get a stats page mock done as well.

Thanks,
Cassiano
